language: c

# explicitly request container-based infrastructure
sudo: false

matrix:
  include:
    - env: GHCVER=7.8.4 ARGS=""
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.2 ARGS=""
      addons: {apt: {packages: [ghc-7.10.2],sources: [hvr-ghc]}}
    - env: GHCVER=head ARGS="--skip-ghc-check"
      addons: {apt: {packages: [ghc-head],  sources: [hvr-ghc]}}
  allow_failures:
     - env: GHCVER=head

before_install:
 - export STACK_YAML=stack-$GHCVER.yaml
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 # stack
 - mkdir -p ~/.local/bin
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - export PATH=~/.local/bin:$PATH

install:
 - stack build

script:
 - stack test

cache:
  directories:
    - $HOME/.stack
